// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package lambchain

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Suma         protoreflect.MessageDescriptor
	fd_Suma_id      protoreflect.FieldDescriptor
	fd_Suma_op1     protoreflect.FieldDescriptor
	fd_Suma_op2     protoreflect.FieldDescriptor
	fd_Suma_res     protoreflect.FieldDescriptor
	fd_Suma_creator protoreflect.FieldDescriptor
)

func init() {
	file_lambchain_lambchain_suma_proto_init()
	md_Suma = File_lambchain_lambchain_suma_proto.Messages().ByName("Suma")
	fd_Suma_id = md_Suma.Fields().ByName("id")
	fd_Suma_op1 = md_Suma.Fields().ByName("op1")
	fd_Suma_op2 = md_Suma.Fields().ByName("op2")
	fd_Suma_res = md_Suma.Fields().ByName("res")
	fd_Suma_creator = md_Suma.Fields().ByName("creator")
}

var _ protoreflect.Message = (*fastReflection_Suma)(nil)

type fastReflection_Suma Suma

func (x *Suma) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Suma)(x)
}

func (x *Suma) slowProtoReflect() protoreflect.Message {
	mi := &file_lambchain_lambchain_suma_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Suma_messageType fastReflection_Suma_messageType
var _ protoreflect.MessageType = fastReflection_Suma_messageType{}

type fastReflection_Suma_messageType struct{}

func (x fastReflection_Suma_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Suma)(nil)
}
func (x fastReflection_Suma_messageType) New() protoreflect.Message {
	return new(fastReflection_Suma)
}
func (x fastReflection_Suma_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Suma
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Suma) Descriptor() protoreflect.MessageDescriptor {
	return md_Suma
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Suma) Type() protoreflect.MessageType {
	return _fastReflection_Suma_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Suma) New() protoreflect.Message {
	return new(fastReflection_Suma)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Suma) Interface() protoreflect.ProtoMessage {
	return (*Suma)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Suma) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_Suma_id, value) {
			return
		}
	}
	if x.Op1 != int32(0) {
		value := protoreflect.ValueOfInt32(x.Op1)
		if !f(fd_Suma_op1, value) {
			return
		}
	}
	if x.Op2 != int32(0) {
		value := protoreflect.ValueOfInt32(x.Op2)
		if !f(fd_Suma_op2, value) {
			return
		}
	}
	if x.Res != int32(0) {
		value := protoreflect.ValueOfInt32(x.Res)
		if !f(fd_Suma_res, value) {
			return
		}
	}
	if x.Creator != "" {
		value := protoreflect.ValueOfString(x.Creator)
		if !f(fd_Suma_creator, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Suma) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "lambchain.lambchain.Suma.id":
		return x.Id != uint64(0)
	case "lambchain.lambchain.Suma.op1":
		return x.Op1 != int32(0)
	case "lambchain.lambchain.Suma.op2":
		return x.Op2 != int32(0)
	case "lambchain.lambchain.Suma.res":
		return x.Res != int32(0)
	case "lambchain.lambchain.Suma.creator":
		return x.Creator != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: lambchain.lambchain.Suma"))
		}
		panic(fmt.Errorf("message lambchain.lambchain.Suma does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Suma) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "lambchain.lambchain.Suma.id":
		x.Id = uint64(0)
	case "lambchain.lambchain.Suma.op1":
		x.Op1 = int32(0)
	case "lambchain.lambchain.Suma.op2":
		x.Op2 = int32(0)
	case "lambchain.lambchain.Suma.res":
		x.Res = int32(0)
	case "lambchain.lambchain.Suma.creator":
		x.Creator = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: lambchain.lambchain.Suma"))
		}
		panic(fmt.Errorf("message lambchain.lambchain.Suma does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Suma) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "lambchain.lambchain.Suma.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "lambchain.lambchain.Suma.op1":
		value := x.Op1
		return protoreflect.ValueOfInt32(value)
	case "lambchain.lambchain.Suma.op2":
		value := x.Op2
		return protoreflect.ValueOfInt32(value)
	case "lambchain.lambchain.Suma.res":
		value := x.Res
		return protoreflect.ValueOfInt32(value)
	case "lambchain.lambchain.Suma.creator":
		value := x.Creator
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: lambchain.lambchain.Suma"))
		}
		panic(fmt.Errorf("message lambchain.lambchain.Suma does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Suma) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "lambchain.lambchain.Suma.id":
		x.Id = value.Uint()
	case "lambchain.lambchain.Suma.op1":
		x.Op1 = int32(value.Int())
	case "lambchain.lambchain.Suma.op2":
		x.Op2 = int32(value.Int())
	case "lambchain.lambchain.Suma.res":
		x.Res = int32(value.Int())
	case "lambchain.lambchain.Suma.creator":
		x.Creator = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: lambchain.lambchain.Suma"))
		}
		panic(fmt.Errorf("message lambchain.lambchain.Suma does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Suma) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "lambchain.lambchain.Suma.id":
		panic(fmt.Errorf("field id of message lambchain.lambchain.Suma is not mutable"))
	case "lambchain.lambchain.Suma.op1":
		panic(fmt.Errorf("field op1 of message lambchain.lambchain.Suma is not mutable"))
	case "lambchain.lambchain.Suma.op2":
		panic(fmt.Errorf("field op2 of message lambchain.lambchain.Suma is not mutable"))
	case "lambchain.lambchain.Suma.res":
		panic(fmt.Errorf("field res of message lambchain.lambchain.Suma is not mutable"))
	case "lambchain.lambchain.Suma.creator":
		panic(fmt.Errorf("field creator of message lambchain.lambchain.Suma is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: lambchain.lambchain.Suma"))
		}
		panic(fmt.Errorf("message lambchain.lambchain.Suma does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Suma) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "lambchain.lambchain.Suma.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "lambchain.lambchain.Suma.op1":
		return protoreflect.ValueOfInt32(int32(0))
	case "lambchain.lambchain.Suma.op2":
		return protoreflect.ValueOfInt32(int32(0))
	case "lambchain.lambchain.Suma.res":
		return protoreflect.ValueOfInt32(int32(0))
	case "lambchain.lambchain.Suma.creator":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: lambchain.lambchain.Suma"))
		}
		panic(fmt.Errorf("message lambchain.lambchain.Suma does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Suma) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in lambchain.lambchain.Suma", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Suma) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Suma) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Suma) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Suma) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Suma)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		if x.Op1 != 0 {
			n += 1 + runtime.Sov(uint64(x.Op1))
		}
		if x.Op2 != 0 {
			n += 1 + runtime.Sov(uint64(x.Op2))
		}
		if x.Res != 0 {
			n += 1 + runtime.Sov(uint64(x.Res))
		}
		l = len(x.Creator)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Suma)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Creator) > 0 {
			i -= len(x.Creator)
			copy(dAtA[i:], x.Creator)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Creator)))
			i--
			dAtA[i] = 0x2a
		}
		if x.Res != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Res))
			i--
			dAtA[i] = 0x20
		}
		if x.Op2 != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Op2))
			i--
			dAtA[i] = 0x18
		}
		if x.Op1 != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Op1))
			i--
			dAtA[i] = 0x10
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Suma)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Suma: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Suma: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Op1", wireType)
				}
				x.Op1 = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Op1 |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Op2", wireType)
				}
				x.Op2 = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Op2 |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Res", wireType)
				}
				x.Res = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Res |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Creator = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: lambchain/lambchain/suma.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suma struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Op1     int32  `protobuf:"varint,2,opt,name=op1,proto3" json:"op1,omitempty"`
	Op2     int32  `protobuf:"varint,3,opt,name=op2,proto3" json:"op2,omitempty"`
	Res     int32  `protobuf:"varint,4,opt,name=res,proto3" json:"res,omitempty"`
	Creator string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *Suma) Reset() {
	*x = Suma{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lambchain_lambchain_suma_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Suma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suma) ProtoMessage() {}

// Deprecated: Use Suma.ProtoReflect.Descriptor instead.
func (*Suma) Descriptor() ([]byte, []int) {
	return file_lambchain_lambchain_suma_proto_rawDescGZIP(), []int{0}
}

func (x *Suma) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Suma) GetOp1() int32 {
	if x != nil {
		return x.Op1
	}
	return 0
}

func (x *Suma) GetOp2() int32 {
	if x != nil {
		return x.Op2
	}
	return 0
}

func (x *Suma) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

func (x *Suma) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

var File_lambchain_lambchain_suma_proto protoreflect.FileDescriptor

var file_lambchain_lambchain_suma_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x6c, 0x61, 0x6d, 0x62,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x75, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x6c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x6c, 0x61, 0x6d, 0x62,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x66, 0x0a, 0x04, 0x53, 0x75, 0x6d, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6f, 0x70, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70, 0x31, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x70, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70,
	0x32, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x42, 0xb7, 0x01,
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x6c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e,
	0x6c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x09, 0x53, 0x75, 0x6d, 0x61, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64,
	0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2f, 0x6c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xa2, 0x02, 0x03, 0x4c,
	0x4c, 0x58, 0xaa, 0x02, 0x13, 0x4c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x4c,
	0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xca, 0x02, 0x13, 0x4c, 0x61, 0x6d, 0x62, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5c, 0x4c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0xe2, 0x02,
	0x1f, 0x4c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x4c, 0x61, 0x6d, 0x62, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x14, 0x4c, 0x61, 0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x4c, 0x61,
	0x6d, 0x62, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lambchain_lambchain_suma_proto_rawDescOnce sync.Once
	file_lambchain_lambchain_suma_proto_rawDescData = file_lambchain_lambchain_suma_proto_rawDesc
)

func file_lambchain_lambchain_suma_proto_rawDescGZIP() []byte {
	file_lambchain_lambchain_suma_proto_rawDescOnce.Do(func() {
		file_lambchain_lambchain_suma_proto_rawDescData = protoimpl.X.CompressGZIP(file_lambchain_lambchain_suma_proto_rawDescData)
	})
	return file_lambchain_lambchain_suma_proto_rawDescData
}

var file_lambchain_lambchain_suma_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lambchain_lambchain_suma_proto_goTypes = []interface{}{
	(*Suma)(nil), // 0: lambchain.lambchain.Suma
}
var file_lambchain_lambchain_suma_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lambchain_lambchain_suma_proto_init() }
func file_lambchain_lambchain_suma_proto_init() {
	if File_lambchain_lambchain_suma_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lambchain_lambchain_suma_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Suma); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lambchain_lambchain_suma_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lambchain_lambchain_suma_proto_goTypes,
		DependencyIndexes: file_lambchain_lambchain_suma_proto_depIdxs,
		MessageInfos:      file_lambchain_lambchain_suma_proto_msgTypes,
	}.Build()
	File_lambchain_lambchain_suma_proto = out.File
	file_lambchain_lambchain_suma_proto_rawDesc = nil
	file_lambchain_lambchain_suma_proto_goTypes = nil
	file_lambchain_lambchain_suma_proto_depIdxs = nil
}
