// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: lambchain/lambchain/tx.proto

package lambchain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName = "/lambchain.lambchain.Msg/UpdateParams"
	Msg_CreateSuma_FullMethodName   = "/lambchain.lambchain.Msg/CreateSuma"
	Msg_UpdateSuma_FullMethodName   = "/lambchain.lambchain.Msg/UpdateSuma"
	Msg_DeleteSuma_FullMethodName   = "/lambchain.lambchain.Msg/DeleteSuma"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateSuma(ctx context.Context, in *MsgCreateSuma, opts ...grpc.CallOption) (*MsgCreateSumaResponse, error)
	UpdateSuma(ctx context.Context, in *MsgUpdateSuma, opts ...grpc.CallOption) (*MsgUpdateSumaResponse, error)
	DeleteSuma(ctx context.Context, in *MsgDeleteSuma, opts ...grpc.CallOption) (*MsgDeleteSumaResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSuma(ctx context.Context, in *MsgCreateSuma, opts ...grpc.CallOption) (*MsgCreateSumaResponse, error) {
	out := new(MsgCreateSumaResponse)
	err := c.cc.Invoke(ctx, Msg_CreateSuma_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSuma(ctx context.Context, in *MsgUpdateSuma, opts ...grpc.CallOption) (*MsgUpdateSumaResponse, error) {
	out := new(MsgUpdateSumaResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateSuma_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteSuma(ctx context.Context, in *MsgDeleteSuma, opts ...grpc.CallOption) (*MsgDeleteSumaResponse, error) {
	out := new(MsgDeleteSumaResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteSuma_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateSuma(context.Context, *MsgCreateSuma) (*MsgCreateSumaResponse, error)
	UpdateSuma(context.Context, *MsgUpdateSuma) (*MsgUpdateSumaResponse, error)
	DeleteSuma(context.Context, *MsgDeleteSuma) (*MsgDeleteSumaResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateSuma(context.Context, *MsgCreateSuma) (*MsgCreateSumaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSuma not implemented")
}
func (UnimplementedMsgServer) UpdateSuma(context.Context, *MsgUpdateSuma) (*MsgUpdateSumaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSuma not implemented")
}
func (UnimplementedMsgServer) DeleteSuma(context.Context, *MsgDeleteSuma) (*MsgDeleteSumaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSuma not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSuma_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSuma)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSuma(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateSuma_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSuma(ctx, req.(*MsgCreateSuma))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSuma_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSuma)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSuma(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateSuma_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSuma(ctx, req.(*MsgUpdateSuma))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteSuma_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteSuma)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteSuma(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteSuma_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteSuma(ctx, req.(*MsgDeleteSuma))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lambchain.lambchain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateSuma",
			Handler:    _Msg_CreateSuma_Handler,
		},
		{
			MethodName: "UpdateSuma",
			Handler:    _Msg_UpdateSuma_Handler,
		},
		{
			MethodName: "DeleteSuma",
			Handler:    _Msg_DeleteSuma_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lambchain/lambchain/tx.proto",
}
